import sys


text = r"""
______  _____  ___                                      _     _
| ___ \/  ___|/ _ \                                    | |   | |
| |_/ /\ `--./ /_\ \_ __ _ __ ___   __ _  __ _  ___  __| | __| | ___  _ __
|    /  `--. \  _  | '__| '_ ` _ \ / _` |/ _` |/ _ \/ _` |/ _` |/ _ \| '_ \
| |\ \ /\__/ / | | | |  | | | | | | (_| | (_| |  __/ (_| | (_| | (_) | | | |
\_| \_|\____/\_| |_/_|  |_| |_| |_|\__,_|\__, |\___|\__,_|\__,_|\___/|_| |_|
                                          __/ |
                                         |___/

Written by M1gnus && Lotus -- Guest starring: AquilaIrreale -- PGIATASTI
"""

credits_text = """
Written by Vittorio aka M1gnus and Nalin aka L07u5
Guest starring Simone aka AquilaIrreale

Glory to PGiatasti:
    - Vittorio aka M1gnus
    - Alessio aka Alexius
    - Cristiano aka ReverseBrain
    - Riccardo aka ODGrip
    - Nalin aka Lotus
    - Emanuele aka KaiserSource
    - Federico aka Heichou
    - Antonio aka CoffeeStraw

https://pgiatasti.it/ -- -- Visit our site to discover more about us
"""


_print = print
def print():
    _print(text, file=sys.stderr)


def credits():
    _print(credits_text, file=sys.stderr)

#TODO: make autogenerated
def show_attacks():
    print("""
======    Implemented     ======
===            14            ===
================================

Attack <requirements: required, [alternative1 | alternative2]>

hastad <n-multi>
mersenne <n>
fermat <n>
qicheng <n>
wiener <n,e>
common_factor <n-multi>
p_1 <n>
factordb <n>
boneh_durfee <n,e>
common_modulus <n, e-multi>
novelty <n>
londahl <n>
smallfraction <n>
smallfactor <n>
""", file=sys.stderr)


def version():
    print("RSArmageddon v.1.0 --Athena--", file=sys.stderr)
